"""Add password_hash column to users table

Revision ID: 592117439ed1
Revises: 
Create Date: 2024-04-26 16:24:19.749087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592117439ed1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
